import Head from 'next/head'
import NavDesktop from '../components/navigation/navigation-desktop'
import NavMobile from '../components/navigation/navigation-mobile/Index'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className=" ">
                <div className="hidden sm:block flex justify-between items-center h-24 bg-black text-white relative shadow-sm font-mono w-full">
                    <NavDesktop />
                </div>
            </header>
            <main className="h-screen dark:bg-slate-800">
                <NavMobile className=" relative  " />
                <h1 className="text-3xl font-bold  text-center ">
                    Welcome to Next.js!
                </h1>
                <p className="">
                    Get started by editing{' '}
                    <code className="">pages/index.js</code>
                </p>
            </main>
        </>
    )
}
